Add item requests
AlexF0890/java-shareit pull request #3
Opened 2023-02-21 09:59 UTC by AlexF0890

2023-02-21 16:55 UTC, EugeneLenkevich requested changes
Привет, Александр, спасибо за PR

Тесты мне понравились  :)
Давай только немножко с методами репозиторием разберемся, посмотри комментарии ниже, пожалуйста

2023-02-21 16:55 UTC, EugeneLenkevich commented on db/shareit.trace.db
> +General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/alex/Desktop/dev/java-shareit/db/shareit.mv.db [2.1.214/7]" [50000-214]
Этот файл наверно не стоит комитить, можно добавить его в .gitignore :)

2023-02-21 16:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findByBookerIdOrderByBookerId(Pageable page);
![image](https://user-images.githubusercontent.com/109306643/220407511-c91b64f6-8599-495a-9443-c7f70020c0b0.png)


В объекте Pageable уже есть возможность задать сортировку, попробуй, может получится указать через него,  т.е. не прибивать ее гвоздями указывая в самом запросе? :)
Ниже в общем то аналогично :)

2023-02-21 16:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findByBookerIdOrderByBookerId(Long bookerId);
Можно было назвать метод  и передать в него pageable, тогда бы можно было не указывать query :)

findByBookerId(pageable)

2023-02-21 16:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +         if (!booking.getItem().getOwner().getId().equals(userId) &&
А еще можно было доработать запрос(добавить условие) так, чтобы данные, к которым нет доступа,  вовсе бы  не находились :)

2023-02-21 16:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ALL:
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-02-21 16:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            state = STATE.valueOf(string);
У нас уже есть обработка

![image](https://user-images.githubusercontent.com/109306643/220408787-76351789-1de4-4887-955a-7afd44bc381c.png)

а получится ли убрать  эту проверку с try-catch и использовать единый механизм? :)

2023-02-21 16:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/CommentService.java
> +    CommentDto addComment(Long itemId, Long userId, CommentDtoCreation commentDtoCreation);
А что если метод назвать просто add, класс CommentService, из названия в пинц пе понятно что он работает с комментариями :)

2023-02-21 23:29 UTC, AlexF0890 commented on db/shareit.trace.db
> +General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/alex/Desktop/dev/java-shareit/db/shareit.mv.db [2.1.214/7]" [50000-214]
не понял немного

2023-02-21 23:29 UTC, AlexF0890 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            state = STATE.valueOf(string);
Не получилось

2023-02-22 05:35 UTC, EugeneLenkevich commented on db/shareit.trace.db
> +General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/alex/Desktop/dev/java-shareit/db/shareit.mv.db [2.1.214/7]" [50000-214]
Вот это

![image](https://user-images.githubusercontent.com/109306643/220532066-7c5c7851-a0cb-4193-9b8b-249930922b17.png)

2023-02-22 05:36 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-22 05:39 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            state = STATE.valueOf(string);
Можно было попробовать добавить новый элемент в enum, например UNKNOWN

2023-04-10 08:51 UTC, merged